### ISSUE TITLE
MacRuby Support

### ISSUE THREAD

**Issue by rvalente** [Fingertips/passengerpane#10]
Are there any plans to implement the support of MacRuby instead of RubyCocoa after the next update of MacRuby is released?

**Comment by alloy** [comment]
Once MacRuby is mature enough, yes, definitely. From [the blog post](http://www.fngtps.com/2009/09/new-os-more-pane-passenger-preference-pane-v1-3):

> The real problem in getting the Passenger preference pane to run in 64-bit mode would be that System Preferences.app wants to use the Objective-C garbage collector. And rightfully so. But the only way to support this easily would be to use MacRuby, which as of yet is not stable enough. But expect the next version of the preference pane to use MacRuby and be a happy 10.6 citizen.
