### ISSUE TITLE
Nginx?

### ISSUE THREAD

**Issue by tvongaza** [Fingertips/passengerpane#11]
With passenger supporting nginx, it being less of a memory hog then apache, plus it being super easy to install on osx (sudo passenger-install-nginx-module)... has there been any thoughts on adding support for it?

The syntax is dead easy:
    server {
        listen 80;
        server_name www.foo.com;
        root /webapps/foo/public;   # <--- notice the 'public' part
        passenger_enabled on;       # <--- don't forget this!
    }

Cheers,
Tys

**Comment by alloy** [comment]
No support for Nginx is planned.

Simply put, we support what we use ourselves, and for development the defaults on the system (Apache) are good enough. However, I can see that some might want to use Nginx, so we will accept patches for it.

HTH

**Comment by tvongaza** [comment]
I might give it a stab, never worked with RubyCocoa so it might be a good learning experience.
