### ISSUE TITLE
Invalid URL in README.rdoc

### ISSUE THREAD

**Issue by triplef** [Fingertips/passengerpane#13]
The readme references http://www.fngtps.com/files/2/2008/12/PassengerPane-1.3.tgz, which does not exist. The correct URL seems to be:
http://www.fngtps.com/files/2/2009/09/PassengerPane-1.3.tgz

**Comment by alloy** [comment]
Oh you're right, I think I forgot to push some last changes from the office… Will do that tomorrow. Thanks

**Comment by alloy** [comment]
Pushed
