### ISSUE TITLE
Need to open two times system preferences before PassengerPrefPane

### ISSUE THREAD

**Issue by persei** [Fingertips/passengerpane#14]
Everytime that I open the PassengerPrefPane the System Preferences app displays a warning message "System Preference must be restarted to open Passenger Pref Pane"

**Comment by alloy** [comment]
This is because the pref pane is still a 32 bit version, as noted in the blog post: http://www.fngtps.com/2009/09/new-os-more-pane-passenger-preference-pane-v1-3
