### ISSUE TITLE
Tail a logfile for an application

### ISSUE THREAD

**Issue by tonycoco** [Fingertips/passengerpane#16]
Something like,
### 

log_dir = File.join(@path, 'log')
FileUtils.mkdir(log_dir) unless File.exist?(log_dir)
log_file = self.environment == 0 ? "development.log" : "production.log"
Kernel.system('/usr/bin/open', File.join(log_dir, log_file))
### 

That should work to open the logs in Console.app!

**Comment by alloy** [comment]
It sounds like an interesting idea. If you have a more elaborate patch, I'd love to look at if this is something we want in. Thanks.

**Comment by alloy** [comment]
Any update on this?

**Comment by tvandervossen** [comment]
This is a feature you would need relatively frequently while you are working on your Rails app so I don’t really see a place for it in the Passenger preference pane. According to the HIG, a "preference should be a setting that the user changes infrequently".

**Comment by tonycoco** [comment]
I don't really think so. If you abide by that argument we shouldn't have the restart button there either. Or even, the PreferencePane all together.
