### ISSUE TITLE
Doesn't work with ruby 1.9

### ISSUE THREAD

**Issue by adamsalter** [Fingertips/passengerpane#18]
Passenger prefpane doesn't work with ruby1.9 installed.

Kind of hard to give a way for you to test this, but:
- install ruby1.9 with MacPorts
- set ruby1.9 as the default (change the /usr/bin/ruby etc. to point to /opt/local/bin/ruby1.9 version)
- install ruby compliled passenger and passenger module.
- restart apache.

Everything works as before, but passenger prefpane gives errors about not being able to save, and doesn't save any changes.

Thanks for a great prefpane,

**Comment by alloy** [comment]
You shouldn't touch /usr/bin, stuff like the pane that may depend on it will break.

It would still be fairly easy to fix this in the pref pane, but like I said, you shouldn't be changing anything that comes with the system in /usr/bin in the first place.

If you want to use a different Ruby yourself, then simply make sure that that Ruby is in front of /usr/bin in your PATH.

PS: If some blog post advised to do install Ruby 1.9 this way, please tell them to not do that.

Thanks

**Comment by alloy** [comment]
I should add, if you do really want this to work this way, make sure the config_installer.rb and config_uninstaller.rb are being executed by the right Ruby. I suspect that is the problem, check the logs in Console.app for more info.

Cheers

**Comment by adamsalter** [comment]
NVM...

That works... Umm re-symlinking /usr/bin/ruby was my solution after many different configurations... the default /usr/bin/ruby\* files are only symlinks anyway.

I've also encountered trouble with the /usr/bin/rails and using ruby1.9 since it uses /usr/bin/env ruby... Anyway, thanks. ;)

**Comment by alloy** [comment]
Well, I guess I could change the passenger pane to use the actual bin in /System instead of /usr/bin. I'll open a new ticket for that. Thanks for the discussion :)
