### ISSUE TITLE
Prefpane hangs on load. (Moved here from LH #35)

### ISSUE THREAD

**Issue by alloy** [Fingertips/passengerpane#2]
Ryan Davis:

“I've got the same issue (with the same console output) as ticket #13022. However, I'm on stock osx 10.5.6 w/ all updates applied w/ stock ruby and xcode + iphone sdk installed. So, I'm very up to date.

{{{ % grep 13 /System/Library/Frameworks/RubyCocoa.framework/Versions/A/Resources/version.plist

<string>0.13.1</string>
<string>0.13.1</string>

}}}

So... it seems to meet the requirements as described in the doco... clue me?”

**Comment by alloy** [comment]
Lucas Húngaro:

“After I updated XCode from 3.0 to 3.1.2 I had the same problem and managed to solve it by manually installing RubyCocoa 0.13.2 from http://is.gd/EiR6 - the odd thing is that I use Mac OS 10.5.7 and should have RubyCocoa 0.13.2 (as described in the passengerpane docs), but had 0.13.1 instead too.”

**Comment by attilagyorffy** [comment]
I had the same problem on 10.5.7 and the above solution works perfectly. Thanks!

**Comment by rswolff** [comment]
+1 for the solution identified above

**Comment by CraigThatcher** [comment]
agree, struggled for months and update of rubyCocoa to 13.2 finally got it working.  hopefully snow leopard won't break this during the upgrade.

**Comment by gbenedict** [comment]
I'm on a Leopard to Snow Leopard update and already have 0.13.2. Same issue with the hang.

**Comment by alloy** [comment]
The RubyCocoa 0.13.2 of SL does not work with the pref pane at all, most have reported more success with the 0.13.2 that's downloadable as a binary. But I will have to take a look at the current state of things anyways. So I'll try to work some on it the coming week and come up with a stable version for SL.

**Comment by radar** [comment]
I'm still encountering this issue after installing it from the latest master.

**Comment by alloy** [comment]
Do you have a version of RubyCocoa installed in /Library/Frameworks ?

**Comment by radar** [comment]
Yes, I've installed 1.0.0 to get LimeChat to work.

**Comment by alloy** [comment]
Always fix the path in the Passenger.prefPane binary to link against the RubyCocoa.framework inside the bundle, even when another version is installed in /Library/Frameworks.

Closed by 844ecb270ce56cae25315aaae2810f8da752d2b4.

**Comment by alloy** [comment]
Ok, building it on a machine that has a RubyCocoa version installed in /Library/Frameworks caused the binary to link against that version instead of the bundled one. This should now be fixed in the above commit. If someone feels adventurous they can try it out, but please note that I still have a few things I'd like to finish before I will make a proper release.

The most important thing to mind is that hostnames are registered, if you wish so, but aliases not yet.

**Comment by radar** [comment]
I've pulled the latest and it is now showing "public.local" as the hostname when I select an app called "rboard" :) I'll file another issue for this.

**Comment by alloy** [comment]
Judging by this and the other ticket, can I assume it's working now? :)

**Comment by radar** [comment]
Yup, thanks!

**Comment by alloy** [comment]
Thanks for verifying.
