### ISSUE TITLE
Websharing over network

### ISSUE THREAD

**Issue by exceptionraiser** [Fingertips/passengerpane#22]
How can I share my passenger urls over web sharing. I'm working with someone on a webapp and I'd like them to be able to view it on their computer before it worked. They would put in my local ip (192.168.0.135:3000) and they could view the app. Is that possible now with passenger somehow? Thanks so much!!!

**Comment by alloy** [comment]
At the moment there’s no automated way to do this.

You can, however, edit the other persons /etc/hosts or Host database (man dscl or in the pane source) to point host.local to your machines IP. This works good if you're working on one project for a fair amount of time.

Alternatively you can use the patches in this repo to add bonjour support: http://github.com/kastner/passengerpane

HTH
