### ISSUE TITLE
Changing path to folder doesn't change <directory> directive

### ISSUE THREAD

**Issue by insane-dreamer** [Fingertips/passengerpane#23]
(Using 1.3 version on Snow Leopard. Previous versions worked fine.)

Editing the paths to a vhost folder in the pane correctly updates the DocumentRoot in the respective .conf file, but does not properly change the matching < directory > directive. This happened on multiple vhost confs. (I ended up editing them by hand to fix it.)

**Comment by alloy** [comment]
Only replace the paths in the user_defined_data when writing out. Closed by 536b769e7a2ac9c9852c5a97e196bd66a9404ce9.
