### ISSUE TITLE
RackEnv doesn't work for Rails applications

### ISSUE THREAD

**Issue by insane-dreamer** [Fingertips/passengerpane#24]
The passenger pref pane now sets the RackEnv option (to indicate production or development), instead of RailsEnv. The RackEnv option doesn't seem to work for Rails applications (at least not mine). Could there be the option to set either one, or both?

**Comment by alloy** [comment]
It should theoretically set the appropriate one based on whether or not config/environment.rb exists and it contains Rails::Initializer: http://github.com/alloy/passengerpane/blob/master/app/models/passenger_application.rb#L212

Does yours not contain that maybe?

**Comment by insane-dreamer** [comment]
Yes, my application contains both a config/environment.rb and Rails::Initializer inside of that file. So you're right, it seems your code should detect it. The only thing I can think of (and I haven't checked your code to find out) is whether this is only detected when a new vhost is created, and not  when one is edited? In this case, the vhost already existed (had been using it with a previous version of passenger-pane).

**Comment by alloy** [comment]
It should try to discover it every time, not that that's actually necessary, so I might cache that. But right now I'm clueless as to what the problem could be, so I'll have to have a good look.

**Comment by mantas** [comment]
I've added RailsEnv production/development to apache config files and it seems to solve the problem.

What about adding RailsEnv automatically?

I know, it's hacky etc, but it just works :)

**Comment by alloy** [comment]
I have tried and tried to reproduce this bug, but haven't been able to. Closing it for now, but if any of you could extract an application that causes this or a failing test case, then please file a new one.
