### ISSUE TITLE
Command-line tool

### ISSUE THREAD

**Issue by alloy** [Fingertips/passengerpane#25]
Right now one has to open the directory the rails app resides in in the Finder, open the prefpane and then drag the folder to the prefpane.

Most of the times you're already in the terminal at the right path, so it would be very convenient if you could do something like:

```
$ passengerpane .
```

Which would open the pane and add the application.

**Comment by levifig** [comment]
Great idea! :D

**Comment by george** [comment]
+1 fantastic idea

**Comment by Manfred** [comment]
The next version of Passenger Pane will work through a command-line tool. It's now available as a gem: $ gem install ppane.

You can see how it works with ppane --help. There are some shortcuts not described in the help text: $ sudo ppane . works.

**Comment by levifig** [comment]
Awesome! =D
