### ISSUE TITLE
Can't find Phusion Passenger Apache module

### ISSUE THREAD

**Issue by sdhull** [Fingertips/passengerpane#28]
Just installed Phusion Passenger and the prefpane on my new MBP running Snow Leopard (10.6.2).

Edit:
Well I tried to attach a screenshot so everyone could see exactly what the problem was, but for some reason it doesn't seem to be up anymore.

Anyway I can run passenger-config --version and it says "2.2.7"
But when I open the Passenger prefpane, it says:
"Can’t find the Phusion Passenger Apache module.  Visit http://www.modrails.com for installation instructions."

A little help would be greatly appreciated.

Edit2: I'm guessing I might need to rebuild RubyCocoa (since I'm using Ruby EE, which is obviously not the ruby "that shipped with OSX").  So I'll try that now and report back.

-Steve

**Comment by sdhull** [comment]
OK well I have now tried everything that might help.

I rebuilt Ruby EE with the compiler flag of "enable-shared" so that RubyCocoa will work.  Then I tried installing RubyCocoa from dmg, then I built RubyCocoa from source.  Then I reinstalled Passenger prefPane.  Then I reinstalled Passenger itself.  Then I reinstalled the prefPane again.

No luck.  It still says "Can’t find the Phusion Passenger Apache module.  Visit http://www.modrails.com for installation instructions."

When I go to my projectname.local it just says "It works!"  This is fairly ironic because it is clearly NOT working.  :(

**Comment by sdhull** [comment]
OK I feel sheepish.  Forgot to restart Apache by ticking and unticking "Web Sharing".  :*)

**Comment by alloy** [comment]
Sorry for the delayed response, I didn't receive any notification emails about issues. Anyways, I'm glad you were able to figure it out, cheers :)

**Comment by ghost** [comment]
@sdhull I'm still having the same issue, I tried doing exactly what you did with no success. I'm not using Ruby EE just the regular distro.

Any suggestion on what to do?

**Comment by ghost** [comment]
I looked at the source code and found the 'passenger_installed?' function which is looking at the httpd -t -D DUMP_MODULES for 'passenger_module' I ran that I'm not getting the result back so it looks like the code is behaving as expected however passenger is installed and working on my machine.

~ $ passenger -v
Phusion Passenger version 3.0.2

"Phusion Passenger" is a trademark of Hongli Lai & Ninh Bui.
~ $ which passenger
/usr/local/bin/passenger
~ $ 

Any thoughts as to why it isn't showing up in the apache modules?

**Comment by ghost** [comment]
Solved my own problem.

I was missing the LoadModules in my apache config. Perhaps you could change the the error message to say something to that effect.
