### ISSUE TITLE
Read environments from database.yml

### ISSUE THREAD

**Issue by tonycoco** [Fingertips/passengerpane#29]
Having the pane read from the database.yml of the application file to get the environments (if it is a Rails application) would be beneficial to the people that want to start their app in a custom environment. Also, making that interface element a pop-up selection menu would make more sense. Since, the list would be dynamically generated.

**Comment by Manfred** [comment]
Can you describe in which situation you would use custom environments and why you would want to run your app in this environment?

**Comment by jordan-brough** [comment]
A couple examples: 1) For development-cached environments 2) Using selenium connected to 'test' environment 3) Connecting to a prod db (or prod db mirror) from a dev machine (e.g., to gather stats or test things out on prod DB w/o having to deploy)

**Comment by tonycoco** [comment]
Exactly, we have environments with different database types even, like Oracle. So, our environment is "oracle_development"

**Comment by alloy** [comment]
I see your point. However, we do not need this, at least not for now.

So it would be better if you add the feature, so that it works exactly as you'd want. Then once it works as you want, please do send me a pull request and we can discuss it further.

Thanks!

PS: Closing for now.
