### ISSUE TITLE
Error saving changes in preference pane.

### ISSUE THREAD

**Issue by joshuapinter** [Fingertips/passengerpane#34]
The console gives me the following errors:
10-01-12 8:51:18 AM [0x0-0x5e65e6].com.apple.systempreferences  2010-01-12 08:51:18.675 System Preferences[79453:903] Saving configuration: /private/etc/apache2/passenger_pane_vhosts/central.local.vhost.conf
10-01-12 8:51:18 AM System Preferences[79453]   Error -60031 in AuthorizationExecuteWithPrivileges
10-01-12 8:51:18 AM [0x0-0x5e65e6].com.apple.systempreferences  2010-01-12 08:51:18.684 System Preferences[79453:903] Error -60031 in AuthorizationExecuteWithPrivileges
10-01-12 8:51:18 AM System Preferences[79453]   The command that failed was: `/usr/bin/ruby "/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb" "--- \n- vhostname: \"*:80\"\n  app_type: rails\n  config_path: /private/etc/apache2/passenger_pane_vhosts/central.local.vhost.conf\n  path: /Users/jp/Sites/central\n  environment: development\n  aliases: \"\"\n  host: central.local\n  user_defined_data: \"  <Directory \\\"/Users/jp/Sites/central/public\\\">\\n    Order allow,deny\\n    Allow from all\\n  </Directory>\"\n"'
10-01-12 8:51:18 AM [0x0-0x5e65e6].com.apple.systempreferences  2010-01-12 08:51:18.685 System Preferences[79453:903] The command that failed was:`/usr/bin/ruby "/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb" "--- \n- vhostname: \"*:80\"\n  app_type: rails\n  config_path: /private/etc/apache2/passenger_pane_vhosts/central.local.vhost.conf\n  path: /Users/jp/Sites/central\n  environment: development\n  aliases: \"\"\n  host: central.local\n  user_defined_data: \"  <Directory \\\"/Users/jp/Sites/central/public\\\">\n    Order allow,deny\n    Allow from all\n  </Directory>\"\n"'

**Comment by alloy** [comment]
Does it also fail if you run that complete command yourself from the command-line? And if so, could you investigate what's causing this for you?

For instance, I know one person that had issues because of his custom shell and settings etc.

**Comment by joshuapinter** [comment]
Total newbie here. What would the command be that I would try?

**Comment by alloy** [comment]
The command is the part in the log after ‘The command that failed was:’. In this case:

```
 /usr/bin/ruby "/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb" "--- \n- vhostname: \"*:80\"\n app_type: rails\n config_path: /private/etc/apache2/passenger_pane_vhosts/central.local.vhost.conf\n path: /Users/jp/Sites/central\n environment: development\n aliases: \"\"\n host: central.local\n user_defined_data: \" <Directory \\\"/Users/jp/Sites/central/public\\\">\\n Order allow,deny\\n Allow from all\\n </Directory>\"\n"'
```

**Comment by gokulamurthy** [comment]
I am getting the same error while saving the passenger pane. Do i need to save the virtual host manually. I have entered my projects folder under a .conf file.

**Comment by alloy** [comment]
Could you elaborate what you mean by “I have entered my projects folder under a .conf file.”

And what have you tried?

**Comment by gokulamurthy** [comment]
As per the below link, i have did the passenger pane setup on my mac osx,
http://bit.ly/aiTGXA
After i edited the passenger.conf file, i have started to add my rails projects into the passenger preference pane. But its not getting save. It returns the same above error in console log.

**Comment by gokulamurthy** [comment]
After opened the passenger preference pane, it locks automatically. Once i click the below lock button it prompt me the user name and password of my system, then it returns the below error in console

System Preferences[455] Error -60031 in AuthorizationExecuteWithPrivileges

**Comment by gokulamurthy** [comment]
Guys, please help me to get rid of this error. Passenger preference pane is not getting save the configurations for my projects.

Error in Console:

2/25/10 2:58:58 PM  System Preferences[1445]    Applying changes to Rails application: /Users/gokulamurthy/projects/sellandshop
2/25/10 2:58:58 PM  System Preferences[1445]    Starting Rails application: /Users/gokulamurthy/projects/sellandshop
2/25/10 2:58:58 PM  System Preferences[1445]    Saving configuration: /private/etc/apache2/passenger_pane_vhosts/sellandshop.local.vhost.conf
2/25/10 2:58:58 PM  [0x0-0x57057].com.apple.systempreferences   2010-02-25 14:58:58.856 System Preferences[1445:903] Applying changes to Rails application: /Users/gokulamurthy/projects/sellandshop
2/25/10 2:58:58 PM  [0x0-0x57057].com.apple.systempreferences   2010-02-25 14:58:58.856 System Preferences[1445:903] Starting Rails application: /Users/gokulamurthy/projects/sellandshop
2/25/10 2:58:58 PM  [0x0-0x57057].com.apple.systempreferences   2010-02-25 14:58:58.856 System Preferences[1445:903] Saving configuration: /private/etc/apache2/passenger_pane_vhosts/sellandshop.local.vhost.conf
2/25/10 2:58:58 PM  System Preferences[1445]    Error -60031 in AuthorizationExecuteWithPrivileges
2/25/10 2:58:58 PM  System Preferences[1445]    The command that failed was: `/usr/bin/ruby "/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb" "--- \n- vhostname: \"*:80\"\n  app_type: rails\n  config_path: /private/etc/apache2/passenger_pane_vhosts/sellandshop.local.vhost.conf\n  path: /Users/gokulamurthy/projects/sellandshop\n  environment: development\n  aliases: \"\"\n  host: sellandshop.local\n  user_defined_data: \"  <Directory \\\"/Users/gokulamurthy/projects/sellandshop/public\\\">\\n    Order allow,deny\\n    Allow from all\\n  </Directory>\"\n"'
2/25/10 2:58:58 PM  [0x0-0x57057].com.apple.systempreferences   2010-02-25 14:58:58.868 System Preferences[1445:903] Error -60031 in AuthorizationExecuteWithPrivileges
2/25/10 2:58:58 PM  [0x0-0x57057].com.apple.systempreferences   2010-02-25 14:58:58.870 System Preferences[1445:903] The command that failed was:`/usr/bin/ruby "/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb" "--- \n- vhostname: \"*:80\"\n  app_type: rails\n  config_path: /private/etc/apache2/passenger_pane_vhosts/sellandshop.local.vhost.conf\n  path: /Users/gokulamurthy/projects/sellandshop\n  environment: development\n  aliases: \"\"\n  host: sellandshop.local\n  user_defined_data: \"  <Directory \\\"/Users/gokulamurthy/projects/sellandshop/public\\\">\n    Order allow,deny\n    Allow from all\n  </Directory>\"\n"'

**Comment by alloy** [comment]
Hey, the problem is that AuthorizationExecuteWithPrivileges is a too general error message to actually be able to say anything about. So alas, you will have to debug this on your end, as it's an environment issue in almost all cases…

Try installing it again and ‘for all users’. You also don't need to install RubyCocoa yourself if you're on a recent osx, as the article does suggest. Good luck, and sorry for the lack of a definitive answer.

**Comment by joshuapinter** [comment]
Tried re-installing and all that. Still no joy. Thanks anyway.

**Comment by joshuapinter** [comment]
I was able to get it working manually, ie. without preference pane. So I learned a lot but haven't tried using the passenger pref pane again. I might try it again soon.

**Comment by gokulamurthy** [comment]
I have tried by removing the existing passenger pref pane from the system preferences and installed again with the option "all users in the system". But it doesnt help me. It returns the same error in the console.
