### ISSUE TITLE
403 Forbidden Error on MySQL pages

### ISSUE THREAD

**Issue by primitus** [Fingertips/passengerpane#36]
After installing Passenger pane, I can access static pages of my app via http://myapp.local

However, when I access pages that need to get data from the database (e.g. http://userA.myapp.local), it will show a 403 error saying "You don't have permission to access / on this server." 

I have tried to reinstall MySQL and Passenger but still can't solve the problem. Can you please help? Thanks.

**Comment by alloy** [comment]
Did you add http://userA.myapp.local as an alias? Could you paste the vhost contents?

**Comment by primitus** [comment]
I think I did, please see the following:

```
    <VirtualHost *:80>
      ServerName myapp.local
      ServerAlias *.myapp.local
      DocumentRoot "/Users/Vince/code/myapp/public"
      RailsEnv development
      <Directory "/Users/Vince/code/myapp/public">
        Order allow,deny
        Allow from all
      </Directory>
    </VirtualHost>
```

and etc/host

```
    127.0.0.1   localhost userA.myapp.local 
    255.255.255.255 broadcasthost
    ::1             localhost 
    fe80::1%lo0 localhost
```

Thanks so much for your help

**Comment by linkedbyair** [comment]
I encountered this- I believe the fix was just to mess with permissions on the rails app directory and possibly its parents.

**Comment by alloy** [comment]
Agreed.
