### ISSUE TITLE
Passenger Pane not Loading App

### ISSUE THREAD

**Issue by mberkom** [Fingertips/passengerpane#37]
I installed passenger yesterday along with passenger pane.  After the necessary configuration, I fired up passenger pane only to discover that whenever I attempt to add a new application it isn't actually added.  

I'm running on a OSX Snow Leopard 10.6.2 with version 1.3 of Passenger Pane.

Below is my console log right after I tried to add a new application:

> 1/27/10 8:38:33 AM    com.apple.launchd.peruser.501[234](com.apple.pbs) Throttling respawn: Will start in 10 seconds
> 1/27/10 8:39:01 AM    System Preferences[16138]   Applying changes to Rails application: /Users/mberkom/rubyapps/hitauditor
> 1/27/10 8:39:01 AM    System Preferences[16138]   Starting Rails application: /Users/mberkom/rubyapps/hitauditor
> 1/27/10 8:39:01 AM    System Preferences[16138]   Saving configuration: /private/etc/apache2/passenger_pane_vhosts/hitauditor.local.vhost.conf
> 1/27/10 8:39:01 AM    [0x0-0x189189].com.apple.systempreferences  2010-01-27 08:39:01.676 System Preferences[16138:903] Applying changes to Rails application: /Users/mberkom/rubyapps/hitauditor
> 1/27/10 8:39:01 AM    [0x0-0x189189].com.apple.systempreferences  2010-01-27 08:39:01.676 System Preferences[16138:903] Starting Rails application: /Users/mberkom/rubyapps/hitauditor
> 1/27/10 8:39:01 AM    [0x0-0x189189].com.apple.systempreferences  2010-01-27 08:39:01.676 System Preferences[16138:903] Saving configuration: /private/etc/apache2/passenger_pane_vhosts/hitauditor.local.vhost.conf
> 1/27/10 8:39:02 AM    [0x0-0x189189].com.apple.systempreferences  2010-01-27 08:39:02.198 ruby[16161:e07] Will try to write config(s).
> 1/27/10 8:39:02 AM    [0x0-0x189189].com.apple.systempreferences  2010-01-27 08:39:02.201 ruby[16161:e07] Will add host: hitauditor.local
> 1/27/10 8:39:02 AM    [0x0-0x189189].com.apple.systempreferences  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:28: warning: Insecure world writable dir /usr/bin in PATH, mode 040757
> 1/27/10 8:39:02 AM    [0x0-0x189189].com.apple.systempreferences  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:28:in `system'
> 1/27/10 8:39:02 AM    [0x0-0x189189].com.apple.systempreferences  : Insecure PATH - /usr/bin/dscl localhost -create /Local/Default/Hosts/hitauditor.local IPAddress 127.0.0.1 (SecurityError)
> 1/27/10 8:39:02 AM    [0x0-0x189189].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:28:in`add_to_hosts'
> 1/27/10 8:39:02 AM    [0x0-0x189189].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:26:in `each'
> 1/27/10 8:39:02 AM    [0x0-0x189189].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:26:in`add_to_hosts'
> 1/27/10 8:39:02 AM    [0x0-0x189189].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:85:in `install!'
> 1/27/10 8:39:02 AM    [0x0-0x189189].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:84:in`each'
> 1/27/10 8:39:02 AM    [0x0-0x189189].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:84:in `install!'
> 1/27/10 8:39:02 AM    [0x0-0x189189].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:95

**Comment by alloy** [comment]
Could you take a look at this warning:

> warning: Insecure world writable dir /usr/bin in PATH, mode 040757

This is what it looks like for me:

> drwxr-xr-x  1185 root  wheel  40290 27 jan 15:47 bin

**Comment by mberkom** [comment]
Changed that directory to 755 and now everything works.  Thanks!

**Comment by mberkom** [comment]
Issue closed.

**Comment by alloy** [comment]
Thanks! :)
