### ISSUE TITLE
Should this be creating vhost files and hosts entries for me?

### ISSUE THREAD

**Issue by chrisbloom7** [Fingertips/passengerpane#40]
I've got Apache2 via Macports, and I've applied the changes to the passenger_pane_config.rb file specific to this setup. I've enabled NameVirtualHost, added the passenger directives to the httpd.conf file, restarted Apache, etc., etc., etc.

However, when I add a new site to the panel and click apply, it is never reachable in the browser and the following is logged to Console.app:

> System Preferences[33372:903] No such file or directory - /opt/local/apache2/conf/passenger_pane_vhosts/testapp.local.vhost.conf

I've verified that the _passenger_pane_vhosts_ directory exists. From everything I've read, it looked like PP did the heavy lifting for me when ever I add a new app. Is this not the case and do I need to add a new vhost file a hosts entry for every new app?

**Comment by chrisbloom7** [comment]
OK - I've got it to pickup the vhosts folder (Following the directions at http://blog.abakas.com/2010/01/passenger-and-apache-load-order.html [via issue #35]), but now it's logging a console error:

> /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:3:in `require': no such file to load -- osx/cocoa (LoadError)

**Comment by chrisbloom7** [comment]
> sudo port install rb-cocoa

seems to have fixed _that_ issue, but now it's not saving the configuration files even though it logs a message to Console.app saying that it is:

> 3/16/10 11:40:50 AM    System Preferences[34586]    Saving configuration: /opt/local/apache2/conf/passenger_pane_vhosts/testapp.local.vhost.conf
> 
> 3/16/10 11:40:50 AM    [0x0-0x103103].com.apple.systempreferences    2010-03-16 11:40:50.793 System Preferences[34586:903] Saving configuration: /opt/local/apache2/conf/passenger_pane_vhosts/testapp.local.vhost.conf
> 
> 3/16/10 11:40:59 AM    System Preferences[34586]    PrefPanePassenger#paneWillBecomeActive: Errno::ENOENT: No such file or directory - /opt/local/apache2/conf/passenger_pane_vhosts/testapp.local.vhost.conf
> 
> 3/16/10 11:40:59 AM    [0x0-0x103103].com.apple.systempreferences    2010-03-16 11:40:59.276 System Preferences[34586:903] PrefPanePassenger#paneWillBecomeActive: Errno::ENOENT: No such file or directory - /opt/local/apache2/conf/passenger_pane_vhosts/testapp.local.vhost.conf

**Comment by chrisbloom7** [comment]
Well, I got it narrowed down to a segfault that's triggered whenever 

> require 'osx/cocoa'

is called...

**Comment by alloy** [comment]
From your messages I inflect you also have a custom Ruby instead of using the default Apple one. So yeah, you had to install RubyCocoa yourself then, as you did.

If you require 'osx/cocoa' from irb, does it segfault too?

If so, then there isn't much that I can help you with, besides advise you to use the default Apple Ruby & RubyCocoa. And/or create a MacPorts ticket / email the RubyCocoa mailing list.

PS: Sorry for the delay, was on vacation.

**Comment by chrisbloom7** [comment]
Thanks for the response Eloy. Yes, I am using a version of Ruby installed by MacPorts. `sudo ports install rb-cocoa` did the trick.

**Comment by chrisbloom7** [comment]
Closing
