### ISSUE TITLE
Can't add apps with supposedly stable 1.3

### ISSUE THREAD

**Issue by bitsinmotion** [Fingertips/passengerpane#41]
Downloaded the stable release onto Snow Leopard.  The pane lets me add an app, but it doesn't work when I try to access it with my browser.   And when I re-open the pane, the app isn't there.

I think I'm moving back to Linux for my development.  I've had about all I can stand of this.

**Comment by alloy** [comment]
Good luck.

**Comment by alloy** [comment]
If you do want to figure this out, then please check your logs for any possible clues and paste them here.
