### ISSUE TITLE
Install issues for Snow Leopard 10.6.2

### ISSUE THREAD

**Issue by spletta** [Fingertips/passengerpane#43]
Hi, I'm finally breaking down and submitting a ticket.
I can't get the Passenger PrefsPane to install correctly on Snow Leopard 10.6.2.
After I double click the PrefrencesPane icon to install and give my password.. I get an Apple Prefrences Pane error Warning. "Could not load Passenger preference pane."
The only thing that pops up in the Console utility is:

3/24/10 10:47:25 AM System Preferences[3294]    [NSPrefPaneBundle instantiatePrefPaneObject](/Users/fanboy/Library/PreferencePanes/Passenger.prefPane): principalClass is nil.
3/24/10 10:47:25 AM [0x0-0x12b12b].com.apple.systempreferences  2010-03-24 10:47:25.313 System Preferences[3294:903] [NSPrefPaneBundle instantiatePrefPaneObject](/Users/fanboy/Library/PreferencePanes/Passenger.prefPane): principalClass is nil.

If I need to provide more info let me know.. thanks in advance
Remington

**Comment by alloy** [comment]
Are you using the default Apple supplied Ruby and RubyCocoa? Or did you install any of these yourself?

**Comment by spletta** [comment]
http://www.robbyonrails.com/articles/2010/02/08/installing-ruby-on-rails-passenger-postgresql-mysql-oh-my-zsh-on-snow-leopard-fourth-edition?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+RobbyOnRails+%28Robby+on+Rails%29

Ruby Cocoa I re-installed today with the dmg from the website.

$ ruby -v
ruby 1.8.7 (2009-06-12 patchlevel 174) [i686-darwin10]

$ which ruby
/opt/local/bin/ruby

Does that help?

**Comment by spletta** [comment]
sorry it cut off my message.. before the link I wrote.

I reinstalled ruby from scratch following (link above now) this post.

**Comment by alloy** [comment]
In this article the system Ruby is moved away, this is not a ‘good’ way of doing things and one that we can’t support. The rule of thumb is that the user does _not_ touch anything in /usr. The right way to do this is move your prefix (/opt/local) _before_ /usr in your $PATH.

Also, another problem with these custom setups vs something expected (Apple's default setup) is that version differences can creep in way to easily. For instance, the Ruby version that Robby has installed is 1.8.7 patchlevel 249, yours however is patchlevel 174. And Maybe there are differences in the rb-cocoa port as well, but I don't know that.

So I suggest making the Apple Ruby work again, check if the pane works, then adjust your personal user's $PATH to use your custom Ruby for your own apps.

HTH.

**Comment by alloy** [comment]
Thanks for pointing me to the article btw, I’ve left a comment explaining the same issue. And asked for a motivation :)

http://www.robbyonrails.com/articles/2010/02/08/installing-ruby-on-rails-passenger-postgresql-mysql-oh-my-zsh-on-snow-leopard-fourth-edition#comment-34041

**Comment by spletta** [comment]
yeah of course... and thanks the for advice.. I'll try and cleans things up locally then try again.

**Comment by alloy** [comment]
Thanks, please do let me know how it worked out.

**Comment by spletta** [comment]
So.. I'm back and I have some questions. Actually just one.. whats the best way going about cleaning up the ruby installs on my Dev machine (Snow Leopard)?

**Comment by spletta** [comment]
should I show the results of

$ sudo find /\* -name ruby

?

**Comment by alloy** [comment]
Maybe looking for the irb/erb command line tools is more helpful? If you want to have a pristine OS X ruby installation again, I guess doing an ‘archive and install’ of OS X would be the best option.

HTH

**Comment by spletta** [comment]
yeah.. I think I'll wait on the archive and install for my next mac (6 months).. what about upgrading to ruby 1.9? 

$ sudo find /\* -name irb
Password:
/Applications/eclipse/plugins/org.jruby_1.2.0.9419p2/lib/ruby/1.8/irb
/Applications/NetBeans/NetBeans 6.7.1.app/Contents/Resources/NetBeans/ruby2/jruby-1.2.0/lib/ruby/1.8/irb
/Developer/SDKs/MacOSX10.5.sdk/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb
/Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb
/Library/Frameworks/MacRuby.framework/Versions/0.5/usr/lib/ruby/1.9.0/irb
/Users/fanboy/.rvm/src/ruby-1.9.2-preview1/bin/irb
/Users/fanboy/.rvm/src/ruby-1.9.2-preview1/doc/irb
/Users/fanboy/.rvm/src/ruby-1.9.2-preview1/lib/irb
find: /dev/fd/3: Not a directory
find: /dev/fd/4: Not a directory
/opt/local/bin/irb
/opt/local/lib/ruby/1.8/irb
/opt/local/var/macports/software/ruby/1.8.7-p174_0+darwin+thread_hooks/opt/local/bin/irb
/opt/local/var/macports/software/ruby/1.8.7-p174_0+darwin+thread_hooks/opt/local/lib/ruby/1.8/irb

I think I'll be using Time Machine more often after this : |

**Comment by alloy** [comment]
I wouldn't install Ruby 1.9 in /usr if that’s what you mean. Don't you have the original files anymore? In the article of Robby, he renames them. Eg: /usr/bin/ruby.orig If you do have them, then I guess renaming them back should be enough.

**Comment by spletta** [comment]
No. You're right about archiving and re-installing. I'm going to try using passenger without the Pane in the mean time.  Thanks for your help!
