### ISSUE TITLE
"Could not load passenger preference pane" after OS X update

### ISSUE THREAD

**Issue by elevation** [Fingertips/passengerpane#44]
Anybody else experiencing this? Started happening after the 2010-002 security update

I tried uninstalling/reinstalling the pane without success, here's my console output:

4/1/10 5:05:00 PM System Preferences[6330] [NSPrefPaneBundle instantiatePrefPaneObject](/Library/PreferencePanes/Passenger.prefPane): error occurred during instantiation. 
4/1/10 5:06:18 PM System Preferences[6330] **\* -[PassengerLoader initWithBundle:]: unrecognized selector sent to instance 0x196c71d0 
4/1/10 5:06:18 PM System Preferences[6330] [NSPrefPaneBundle instantiatePrefPaneObject](/Library/PreferencePanes/Passenger.prefPane): error occurred during instantiation.

**Comment by rxw1** [comment]
You probably (re)moved /System/Library/Frameworks/Ruby.framework/Versions/1.8. I moved it, the preference pane stopped working, after putting it back, the preference pane worked again.

HTH, René

**Comment by elevation** [comment]
That doesn't seem to be it, /System/Library/Frameworks/Ruby.framework/Versions/1.8 is intact.  I also just tried rebuilding ruby cocoa from source, and that succeeded, but I still get the same error when trying to load the pref pane.  

Do you have any other suggestions of where I might look to troubleshoot this?

Thanks!

**Comment by knoopx** [comment]
I'm having the same issue. what's wrong with deleting/moving Ruby.framework? Isn't RubyCocoa already bundled?

**Comment by alloy** [comment]
@elevation I have unfortunately been unable to reproduce this on multiple machines… I have started some work on a MacRuby version which would probably fix this issue, but I can't say when that would be done. For now I'll close this. If you have more info on how to reproduce this, please re-open.

**Comment by alloy** [comment]
@knoopx Messing with anything pre-installed in /usr or /System can and will make your install unreliable, as some tools expect specific version to be available. RubyCocoa comes with the system ruby, which is Ruby.framework. If you are not using these version, or have (re)moved them, then there isn't much I can do for you. Except to suggest to make your system install in order again…

HTH
