### ISSUE TITLE
Changing port 80

### ISSUE THREAD

**Issue by bokor** [Fingertips/passengerpane#45]
I haven't been able to figure out how to change to port 80.  When I have updated the code to support a new port (say port 81) it seems to fail without any errors.  I don't know if there is an internal error within the Pane or not but I have tried making all necessary changes (that I saw appropriate).  If this is easy and I'm doing something stupid..sorry for wasting your time.  Thank you for assisting.

**Comment by Manfred** [comment]
Can you explain a bit more about what you're trying to achieve and maybe post a patch of the code you changed?

**Comment by bokor** [comment]
I'm sorry if I wasn't clear before.  I would post a patch if I knew what the problem was but I am trying to run Apache2 on port 81 but when I do that and use passenger pane, it doesn't add the virtual hosts correctly for port 81.  It automatically adds them as port 80.  I don't know if there is an easy way to change this in the code or not.

**Comment by Manfred** [comment]
Yes, that should be relatively easy to change in the code. You just replace every occurrence of :80 to :81.

**Comment by alloy** [comment]
You could replace the hardcoded `:80', in the source, with a constant and define it in the passenger_pane_config.rb file. This way it could be merged back into the main source.

**Comment by bokor** [comment]
I have updated the source and can contribute it back so that you can change the port from a property.

**Comment by alloy** [comment]
Great, can you push your changes to your fork? Or paste the diff here?

**Comment by bokor** [comment]
I didn't create a fork so here are the changes.

passenger_pane_config.rb
     Added VIRTUAL_HOST_PORT = "*:81"

config_installer.rb
     Updated 

```
 def verify_httpd_conf
unless File.read(PassengerPaneConfig::HTTPD_CONF).include? "Include #{PassengerPaneConfig::PASSENGER_APPS_DIR}/*.conf"
  OSX::NSLog("Will try to append passenger pane vhosts conf to: #{PassengerPaneConfig::HTTPD_CONF}")
  File.open(PassengerPaneConfig::HTTPD_CONF, 'a') do |f|
    f << %{
```

# Added by the Passenger preference pane

# Make sure to include the Passenger configuration (the LoadModule,

# PassengerRoot, and PassengerRuby directives) before this section.

<IfModule passenger_module>
  NameVirtualHost #{PassengerPaneConfig::VIRTUAL_HOST_PORT}
  <VirtualHost #{PassengerPaneConfig::VIRTUAL_HOST_PORT}>
    ServerName _default_
  </VirtualHost>
  Include #{PassengerPaneConfig::PASSENGER_APPS_DIR}/*.conf
</IfModule>}
      end
    end
  end

  def create_vhost_conf(index)
    app = @data[index]
    public_dir = File.join(app['path'], 'public')
    vhost = [
      "<VirtualHost #{PassengerPaneConfig::VIRTUAL_HOST_PORT}>",
      "  ServerName #{app['host']}",
      ("  ServerAlias #{app['aliases']}" unless app['aliases'].empty?),
      "  DocumentRoot \"#{public_dir}\"",
      "  RailsEnv #{app['environment']}",
      (app['user_defined_data'] unless app['user_defined_data'].empty?),
      "</VirtualHost>"
    ].compact.join("\n")

```
OSX::NSLog("Will write vhost file: #{app['config_path']}\nData: #{vhost}")
File.open(app['config_path'].bypass_safe_level_1, 'w') { |f| f << vhost }
```

  end

**Comment by bokor** [comment]
came out not looking good...I hope you get what you need....if not then I can update it another way
