### ISSUE TITLE
Insecure World Writable Dir...

### ISSUE THREAD

**Issue by exceptionraiser** [Fingertips/passengerpane#46]
I just reinstalled and I think I have some privilege issues but not sure what to set where. Here's what the console says:

5/23/10 3:07:38 PM  System Preferences[926] Applying changes to Rails application: /Users/marc/Sites/Rails/thriveapp
5/23/10 3:07:38 PM  System Preferences[926] Starting Rails application: /Users/marc/Sites/Rails/thriveapp
5/23/10 3:07:38 PM  System Preferences[926] Saving configuration: /private/etc/apache2/passenger_pane_vhosts/thrive.local.vhost.conf
5/23/10 3:07:38 PM  [0x0-0x22022].com.apple.systempreferences   2010-05-23 15:07:38.978 System Preferences[926:903] Applying changes to Rails application: /Users/marc/Sites/Rails/thriveapp
5/23/10 3:07:38 PM  [0x0-0x22022].com.apple.systempreferences   2010-05-23 15:07:38.979 System Preferences[926:903] Starting Rails application: /Users/marc/Sites/Rails/thriveapp
5/23/10 3:07:38 PM  [0x0-0x22022].com.apple.systempreferences   2010-05-23 15:07:38.979 System Preferences[926:903] Saving configuration: /private/etc/apache2/passenger_pane_vhosts/thrive.local.vhost.conf
5/23/10 3:07:39 PM  authexec[974]   executing /usr/bin/ruby
5/23/10 3:07:39 PM  [0x0-0x22022].com.apple.systempreferences   2010-05-23 15:07:39.371 ruby[974:e07] Will try to write config(s).
5/23/10 3:07:39 PM  [0x0-0x22022].com.apple.systempreferences   2010-05-23 15:07:39.375 ruby[974:e07] Will add host: thrive.local
5/23/10 3:07:39 PM  [0x0-0x22022].com.apple.systempreferences   /Users/marc/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:28: warning: Insecure world writable dir /usr/bin in PATH, mode 040777
5/23/10 3:07:39 PM  [0x0-0x22022].com.apple.systempreferences   /Users/marc/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:28:in `system': Insecure PATH - /usr/bin/dscl localhost -create /Local/Default/Hosts/thrive.local IPAddress 127.0.0.1 (SecurityError)
5/23/10 3:07:39 PM  [0x0-0x22022].com.apple.systempreferences       from /Users/marc/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:28:in`add_to_hosts'
5/23/10 3:07:39 PM  [0x0-0x22022].com.apple.systempreferences       from /Users/marc/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:26:in `each'
5/23/10 3:07:39 PM  [0x0-0x22022].com.apple.systempreferences       from /Users/marc/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:26:in`add_to_hosts'
5/23/10 3:07:39 PM  [0x0-0x22022].com.apple.systempreferences       from /Users/marc/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:85:in `install!'
5/23/10 3:07:39 PM  [0x0-0x22022].com.apple.systempreferences       from /Users/marc/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:84:in`each'
5/23/10 3:07:39 PM  [0x0-0x22022].com.apple.systempreferences       from /Users/marc/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:84:in `install!'
5/23/10 3:07:39 PM  [0x0-0x22022].com.apple.systempreferences       from /Users/marc/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:95

Any thoughts? Thanks so much.

**Comment by Manfred** [comment]
Can you check the permissions on the /usr/bin directory? I think it's world writeable. It should look like this:

<pre><code>drwxr-xr-x  1098 root  wheel  37332 May 23 15:14 bin</code></pre>

**Comment by exceptionraiser** [comment]
Actually I just repaired permissions and restarted and it works just fine. Thanks so much!

**Comment by Manfred** [comment]
You're welcome, have fun with the pane.
