### ISSUE TITLE
Passenger Pane doesn't recognize a Rails 3 application as a Rails app

### ISSUE THREAD

**Issue by Manfred** [Fingertips/passengerpane#47]
Because of this the configuration snippets contains "RackEnv development" and the application starts in production.

**Comment by alloy** [comment]
Recognize a Rails 3 app.

Closed by 3e3002676e7084e1fe7f6183d6efa24c0e06e2d4, Closed by 3e3002676e7084e1fe7f6183d6efa24c0e06e2d4.
