### ISSUE TITLE
Sets Rack environment rather than Rails

### ISSUE THREAD

**Issue by bokor** [Fingertips/passengerpane#48]
I'm having a problem when I create a rails application and it sets the vhost to Rack environment instead of rails.  Not sure what needs to be done to make this from not happening.  Any help would be appreciated.

**Comment by alloy** [comment]
Recognize a Rails 3 app.

closed by 3e3002676e7084e1fe7f6183d6efa24c0e06e2d4, closed by 3e3002676e7084e1fe7f6183d6efa24c0e06e2d4.

**Comment by bokor** [comment]
Not sure I understand the comment.  I'm using Rails 2.3.6

**Comment by alloy** [comment]
It’s actually the commit message :)

Can you paste your config/environment.rb contents?

**Comment by bokor** [comment]
actually I think it is working..and I didn't change anything DOH!  I'll keep testing it to see if I notice a pattern

**Comment by alloy** [comment]
Ok, thanks :)
