### ISSUE TITLE
Public directory cannot be set independently from app root 

### ISSUE THREAD

**Issue by gaspard** [Fingertips/passengerpane#49]
Here is a patch that adds a "public" directory that you can change if your app does not have a conventional app <--> public relation (multi-site app for example):  http://github.com/gaspard/passengerpane/tree/zena

You do not need to fill the "public" field, it automagically updates from the app root.

Moreover, displaying the folder being served to the public is a nice feature too !

**Comment by tvandervossen** [comment]
This change would add significant visual clutter for an option most people will never need. Did you know you can edit the Apache configuration by dragging an item from the source list onto a text editor?

**Comment by gaspard** [comment]
I am amazed...  

I propose a change with tests, xib file update and nice default behavior (you do not have to set the public path for default aps) and you are worried about "clutter" for a preference pane that nobody spends a lot of time looking at ?

I would understand if I propose to add yet another button to an editor because I want a way to create direct links to my favorite encyclopedia, but we are in a totally different situation: I propose to show the "document root" folder of a website !

**Comment by tvandervossen** [comment]
The quality of your patch is outstanding, no doubt about it. Great work. However, that doesn’t mean it’s going to be accepted when I don’t think the feature improves to the user experience.

**Comment by gaspard** [comment]
I am not saying my work is great, I am not saying you _must_ include it, I just think that rejecting a useful feature is not worth the "clutter" problem.

FYI, my patch for PassengerAppRoot took some time to get accepted in Passenger with arguments just like yours. But if you look at who is using this setting (search forums), it's not Zena users, just other people that happen to have multi-site applications or just store "public" in unconventional places for good reasons.

**Comment by gaspard** [comment]
PS: I just realized that my changes removed empty white-space in some files (a setting in my editor that saves us lots of headaches). I can update the patch to remove these changes if you like.
