### ISSUE TITLE
Using with Nginx instead of Apache?

### ISSUE THREAD

**Issue by millisami** [Fingertips/passengerpane#50]
Hi, can I use this pane with Nginx instead of Apache?

**Comment by Manfred** [comment]
Nope, the Passenger Pane was written to easily configure Rails apps for development. Because Apache ships with Mac OS we only support Apache. You're free to fork the pane and implement Nginx support.

**Comment by alloy** [comment]
There’s a fork with nginx suuport by Crigor: http://github.com/crigor/passengerpane/tree/nginx

**Comment by millisami** [comment]
Thanks, I'll look at it.
