### ISSUE TITLE
Configurations not saved

### ISSUE THREAD

**Issue by aronallen** [Fingertips/passengerpane#51]
# Issue

The files for the new hosts are not created in /private/etc/apache2/pa… 
The hosts are not initialized (something.local)
# Info

My ruby instalation is located within my /opt directory, i changed all the paths in 'passenger_pane_config.rb' to match my instalation.

My 'httpd.conf' is pointing at the passenger gem, within the /opt directory.
# Log

6/9/2010 15:30:37   System Preferences[11557]   Applying changes to Rails application: /Users/aronallen/hello-world
6/9/2010 15:30:37   System Preferences[11557]   Starting Rails application: /Users/aronallen/hello-world
6/9/2010 15:30:37   System Preferences[11557]   Saving configuration: /private/etc/apache2/passenger_pane_vhosts/hello-world.local.vhost.conf
6/9/2010 15:30:37   [0x0-0x203203].com.apple.systempreferences  2010-09-06 15:30:37.854 System Preferences[11557:903] Applying changes to Rails application: /Users/aronallen/hello-world
6/9/2010 15:30:37   [0x0-0x203203].com.apple.systempreferences  2010-09-06 15:30:37.857 System Preferences[11557:903] Starting Rails application: /Users/aronallen/hello-world
6/9/2010 15:30:37   [0x0-0x203203].com.apple.systempreferences  2010-09-06 15:30:37.858 System Preferences[11557:903] Saving configuration: /private/etc/apache2/passenger_pane_vhosts/hello-world.local.vhost.conf
6/9/2010 15:30:38   [0x0-0x203203].com.apple.systempreferences  2010-09-06 15:30:38.079 ruby[11571:e07] Will try to write config(s).
6/9/2010 15:30:38   [0x0-0x203203].com.apple.systempreferences  2010-09-06 15:30:38.083 ruby[11571:e07] Will add host: hello-world.local
6/9/2010 15:30:38   [0x0-0x203203].com.apple.systempreferences  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:28: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
6/9/2010 15:30:38   [0x0-0x203203].com.apple.systempreferences  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:28:in `system': Insecure PATH - /usr/bin/dscl localhost -create /Local/Default/Hosts/hello-world.local IPAddress 127.0.0.1 (SecurityError)
6/9/2010 15:30:38   [0x0-0x203203].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:28:in`add_to_hosts'
6/9/2010 15:30:38   [0x0-0x203203].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:26:in `each'
6/9/2010 15:30:38   [0x0-0x203203].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:26:in`add_to_hosts'
6/9/2010 15:30:38   [0x0-0x203203].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:85:in `install!'
6/9/2010 15:30:38   [0x0-0x203203].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:84:in`each'
6/9/2010 15:30:38   [0x0-0x203203].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:84:in `install!'
6/9/2010 15:30:38   [0x0-0x203203].com.apple.systempreferences      from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:95
6/9/2010 15:30:42   System Preferences[11557]   Restarting Rails application: /Users/aronallen/hello-world
6/9/2010 15:30:42   [0x0-0x203203].com.apple.systempreferences  2010-09-06 15:30:42.292 System Preferences[11557:903] Restarting Rails application: /Users/aronallen/hello-world
6/9/2010 15:30:42   [0x0-0x203203].com.apple.systempreferences  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:144: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777

**Comment by alloy** [comment]
The issue at hand, is this part of the logs:

> warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777

Please see issue #46

**Comment by aronallen** [comment]
Thanks I cleared out alot of the errors, but I still have some.
The files are still not created in the vhosts folder.
#Log

6/9/2010 16:53:50   [0x0-0x47047].com.apple.systempreferences   2010-09-06 16:53:50.840 System Preferences[18232:903] Applying changes to Rails application: /Users/aronallen/hello-world
6/9/2010 16:53:50   [0x0-0x47047].com.apple.systempreferences   2010-09-06 16:53:50.843 System Preferences[18232:903] Starting Rails application: /Users/aronallen/hello-world
6/9/2010 16:53:50   [0x0-0x47047].com.apple.systempreferences   2010-09-06 16:53:50.844 System Preferences[18232:903] Saving configuration: /opt/local/apache2/passenger_pane_vhosts/hello-world.local.vhost.conf
6/9/2010 16:53:50   System Preferences[18232]   Applying changes to Rails application: /Users/aronallen/hello-world
6/9/2010 16:53:50   System Preferences[18232]   Starting Rails application: /Users/aronallen/hello-world
6/9/2010 16:53:50   System Preferences[18232]   Saving configuration: /opt/local/apache2/passenger_pane_vhosts/hello-world.local.vhost.conf
6/9/2010 16:53:51   [0x0-0x47047].com.apple.systempreferences   2010-09-06 16:53:51.082 ruby[18242:e07] Will try to write config(s).
6/9/2010 16:53:51   [0x0-0x47047].com.apple.systempreferences   /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:40:in `read': No such file or directory - /opt/local/apache2/httpd.conf (Errno::ENOENT)
6/9/2010 16:53:51   [0x0-0x47047].com.apple.systempreferences       from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:40:in`verify_httpd_conf'
6/9/2010 16:53:51   [0x0-0x47047].com.apple.systempreferences       from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:82:in `install!'
6/9/2010 16:53:51   [0x0-0x47047].com.apple.systempreferences       from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:95

**Comment by alloy** [comment]
You said that you only have a custom Ruby, which is in /opt, so you should not have changed any of the Apache related path constants. As you can see from the log, it clearly says that this file does not exist: /opt/local/apache2/httpd.conf, as it is probably in the default location /private/etc/apache2/httpd.conf

Finally, there shouldn't be much reason to not use the default Ruby, that ships with osx.

**Comment by aronallen** [comment]
@alloy

I forgot to mention i have a costum instalation of Apache as well, that is located within opt.

I am trying to get everything running, I am following some ruby book, that recomended installing ruby via MacPorts, so that is what i did.

I am suspecting it might be something rb-cocoa releated, though I installed the latest version via macports… (1.0.1)

**Comment by alloy** [comment]
I would try to make it work with the default Ruby, unless you yourself have an explicit reason to not do it that way. (I hope the book didn't advice you to delete the original Ruby?)

It might be a problem with rb-cocoa, but in this case the log is pretty explicit about the problem. Do you have a file at: /opt/local/apache2/httpd.conf ?

**Comment by aronallen** [comment]
@alloy

The book didn't advise me to delete the original ruby. The books title is 'Agine Web Development With Rails'

the path might be the problem, it is located in a sub-directory called ./conf i will just check it out..

**Comment by aronallen** [comment]
The problem is that i set the apache dir to the root folder of the apache instalation, I am now pointing it at the ./conf folder.

maybe renaming the variable to APACHE_CONFIG_DIR instead of APACHE_DIR would be advisable.

I fixed some premesions on dscl and it now seems to work

#Log
