### ISSUE TITLE
Ruby 1.9.2

### ISSUE THREAD

**Issue by jadencarver** [Fingertips/passengerpane#54]
I'm running ruby 1.9.2 for my system ruby, and the preferences pane is hanging. The error I am getting in the console is:

9/23/10 6:35:11 PM  System Preferences[94770]   -[NSCFNumber pathForImageResource:]: unrecognized selector sent to instance 0x18f48b60
9/23/10 6:35:11 PM  [0x0-0x167167].com.apple.systempreferences  2010-09-23 18:35:11.133 System Preferences[94770:903] -[NSCFNumber pathForImageResource:]: unrecognized selector sent to instance 0x18f48b60
9/23/10 6:35:11 PM  System Preferences[94770]   -[NSCFNumber pathForImageResource:]: unrecognized selector sent to instance 0x18f48b60
9/23/10 6:35:11 PM  [0x0-0x167167].com.apple.systempreferences  2010-09-23 18:35:11.135 System Preferences[94770:903] -[NSCFNumber pathForImageResource:]: unrecognized selector sent to instance 0x18f48b60

**Comment by alloy** [comment]
Only OS X defaults are supported and afaik RubyCocoa does not even compile on 1.9.x. So you will have to debug this yourself, or revert your system install to use the default Ruby and RubyCocoa.

PS: It's always a good idea to leave your system installation in tact, as other tools might depend on it as well.

**Comment by jadencarver** [comment]
I didn't realize that RubyCocoa does not compile on 1.9.2. I still have the system ruby inside of /System/Library/Frameworks and will see if I can get it to work. Thank you for your reply.

**Comment by jadencarver** [comment]
I don't know what version I had before, but I just re-downloaded 1.3 and it suddenly works, so my mistake. I probably had an old version.
