### ISSUE TITLE
Removing an alias does not seem to deregister it

### ISSUE THREAD

**Issue by gunn** [Fingertips/passengerpane#56]
My site has some flash resources that expect to talk to the live version of my site e.g. myapp.com . To test it I added an alias in passengerpane to myapp.com in addition to myapp.local as the address. When I'd finished testing I removed the alias and clicked apply. 

Unfortunately this doesn't seem to be enough to properly remove the alias yet.
After some reading of the passengerpane source I found the solution:
    sudo /usr/bin/dscl localhost -delete /Local/Default/Hosts/myapp.com

Would be great if this could be automated.
Note this happened with passengerpane 1.3 but from what I can tell there is no fix in the current code.

**Comment by Manfred** [comment]
Thanks for the ticket. The experimental branch figures out all changes to the hostnames and registers them properly with directory services.
