### ISSUE TITLE
experimental branch crashes when there are no config files

### ISSUE THREAD

**Issue by smsm1** [Fingertips/passengerpane#58]
When you have never used the Passenger Preference Pane before and try to run the experimental branch, the preference pane will just crash. This is due to the following error:
 -[NSCFArray objectAtIndex:]: index (0) beyond bounds (0)

It may also be worthwhile noting that passenger wasn't yet installed. The master branch can cope with both of these cases.

**Comment by Manfred** [comment]
You are very correct sir, launching the Pane without Passenger, and even without applications installed will probably lead to a crash. I wouldn't recommend using the experimental branch for now.

I will keep this in mind when developing and resolve it in time.

**Comment by smsm1** [comment]
Thanks for the update. I like living on the cutting edge, and am happy to test the new development branch.

**Comment by Manfred** [comment]
The error was caused when there were no applications defined yet. I've fixed this yesterday so you can try it again if you want to.
