### ISSUE TITLE
Lion DP 4 unexpected quit

### ISSUE THREAD

**Issue by alexshk** [Fingertips/passengerpane#63]
Openening pp in Lion DP4 causes System Preferences to quit. Here is a [gist with details](https://gist.github.com/1012899).

**Comment by Manfred** [comment]
I ran the pane on preview 4 yesterday and I don't remember it crashing. Does this always happen for you?

**Comment by alexshk** [comment]
Yes, always. And afair in DP3 it was crashing too

**Comment by alloy** [comment]
You are using the 1.3 release version, right? That’s the old RubyCocoa one, please build the current master which has been rewritten and should work on Lion DP.
