### ISSUE TITLE
Off switch

### ISSUE THREAD

**Issue by linkedbyair** [Fingertips/passengerpane#66]
I noticed there are a few Passenger processes always running as soon as I boot my computer. Would be nice to have an "off" switch in the pref pane since I only use it rarely.

(During development I generally use mongrel or webrick since they are integrated with my IDE's debugger, but use Passenger via passengerpane for times when I need to simulate the production environment more closely.)

**Comment by Manfred** [comment]
The off switch is under Sharing in the system preferences:

http://cl.ly/0f1a2Y1O3A0j3o163y47

During normal operation Passenger you only start a spawner and no processes for your applications. You might want to check if you haven't configured PassengerMinInstances anywhere and read the Passenger documentation to make sure you're not keeping processes around.

Also, I wouldn't worry too much about a few processes, they probably won't get in the way of the normal operation of your computer. Mac OS will make sure they're pushed to swap when other applications need the memory.

**Comment by linkedbyair** [comment]
Fair enough, I guess Passenger itself isn't really set up to be started and stopped separate from Apache come to think of it...
